version: '3'
services:
  web:
    build: .
    image: nextjs-app:latest
    container_name: nextjs-app
    ports:
      - "3000:3000"  # Expose the app on port 3000
    volumes:
      - .:/usr/src/app  # Sync local files to the container for live reloading
    environment:
      NODE_ENV: production
