name: Next.js CI with Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for building Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t test-app-nextjs-app:latest .

      # Step 4: Run tests in the Docker container
      #- name: Test the application in Docker
      #  run: docker run --rm test-app-nextjs-app:latest npm run test

      # Step 5: Build the application in Docker (optional, depending on the test)
      - name: Build application in Docker (after tests)
        run: docker run --rm test-app-nextjs-app:latest npm run build
