name: Next.js CI/CD with Docker Build, Test, and Direct Deployment

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-test:
    runs-on: self-hosted  # Uses your self-hosted runner
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Display hostname for debug purposes
      - name: Display Hostname
        run: hostname


      # Step 4: Build the Docker image with docker-compose
      - name: Build Docker Image
        run: docker-compose up --build -d

      # Step 5: Save Docker image as an artifact
      - name: Save Docker Image as Artifact
        run: docker save nextjs-app:latest -o nextjs-app.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-app-image
          path: nextjs-app.tar

      
