name: Next.js CI/CD with Docker Build, Test, and Direct Deployment

on:
  workflow_dispatch:
    
jobs:
  build-and-test:
    runs-on: self-hosted
    
  
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Displaying hostname
      - name: hostname
        run: hostname
        
      # Step 4: Build the Docker image
      - name: Build Docker image
        run:  docker-compose up --build
