name: Next.js CI/CD with Alpine, npm, and Logs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:18-alpine  # Using Alpine image with Node.js

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies (store logs)
      - name: Install dependencies
        run: |
          mkdir -p logs  # Create a directory for logs
          npm install > logs/install.log 2>&1  # Capture the logs of npm install

      # Step 3: Run tests (store logs)
      - name: Run tests
        run: |
          npm test > logs/test.log 2>&1 || true  # Capture the logs of npm test, don't fail the workflow if tests fail

      # Step 4: Build the Next.js application (store logs)
      - name: Build project
        run: |
          npm run build > logs/build.log 2>&1  # Capture the logs of npm run build

      # Step 5: Upload logs as artifacts
      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: build-logs  # Name of the artifact
          path: logs/  # Upload all the log files from the 'logs' directory
