name: Next.js CI/CD with Docker Build, Test, and Direct Deployment

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-test:
    runs-on: self-hosted  # Uses your self-hosted runner
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Display hostname for debug purposes
      - name: Display Hostname
        run: hostname


      

      
